### ISSUE TITLE
parse error with package.json

### ISSUE THREAD

**Issue by kraebsli** [otacke/h5p-portfolio-chapter#3]
I get a parse error with package.json, there is non parseable code inside...

**Comment by otacke** [comment]
Please try again with the latest version.

If you're building this yourself instead of using the latest version which is available at https://www.olivertacke.de/labs/2022/10/25/show-what-you-can-do-with-h5p-portfolio then you should also be capable of spotting what the issue was and create a pull-request to fix it ;-)

**Comment by kraebsli** [comment]
yes i could fix it ;-) and indeed i tried to build it myself. but i thought on github i find the latest version.

**Comment by otacke** [comment]
You'll find the latest code which is not necessarily meant for production, yes.

New releases are published at https://www.olivertacke.de/labs/2022/10/25/show-what-you-can-do-with-h5p-portfolio and listed at https://www.olivertacke.de/labs/h5p-content-types/ until either H5P Group lists the content type on their H5P Hub or some other suitable content type source gets established.

**Comment by kraebsli** [comment]
Ah, ok, thank you. Then I was not on the right track. I will try installation from the links.

**Comment by otacke** [comment]
You can build the libraries from sources, too, currently. Now that I fixed the package.json file, the released version and the version that would be build from source are the same.

If you're not planning to play with the code or to modify if for a particular reason, but only want to have the latest version, I'd recommend to stick with the site mentioned before.
